language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- "pypy"
install:
- pip install pip --upgrade
- pip install requests-mock
- pip install coveralls
- pip install nose nose-parameterized
script:
- coverage run --source=oandapyV20 setup.py test
after_success:
- coveralls
